apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-cluster
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: './charts/workload-cluster'
      version: '0.4.0'
      sourceRef:
        kind: GitRepository
        name: helm-chart
        namespace: flux-system
      interval: 1m
  # values:
  #   workers:
  #     replicas: 1
