apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm-chart
  namespace: flux-system
spec:
  secretRef:
    name: flux-system
  url: ssh://git@github.com/tuladhar/gitops-demo
  interval: 30s
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/ 

