apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: staging-workload-cluster
  namespace: default
spec:
  interval: 30s
  chart:
    spec:
      chart: './charts/workload-cluster'
      version: '0.8.0'
      sourceRef:
        kind: GitRepository
        name: helm-chart
        namespace: flux-system
      interval: 30s
  values:
    workers:
      replicas: 3
